name: awfar_offer_app
description: "awfar_offer_app."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  connectivity_plus: ^6.1.0
  country_code_picker: ^3.1.0
  country_flags: ^3.0.0
  country_picker: ^2.0.27
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  device_info_plus: ^11.2.0
  dio: ^5.7.0
  equatable: ^2.0.7
  firebase_auth: ^5.4.0
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_facebook_auth: ^7.1.1
  flutter_flavorizr: ^2.2.3
  flutter_launcher_icons: ^0.14.1
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.2
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.17
  flutter_timer_countdown: ^1.0.7
  font_awesome_flutter: ^10.8.0
  gap: ^3.0.1
  get_it: ^8.0.1
  google_mobile_ads: ^5.2.0
  google_sign_in: ^6.2.2
  googleapis_auth: ^1.6.0
  internet_connection_checker_plus: ^2.7.0
  intl_phone_number_input: ^0.7.4
  json_annotation: ^4.9.0
  motion_toast: ^2.11.0
  path_provider: ^2.1.5
  persistent_bottom_nav_bar: ^6.2.1
  photo_view: ^0.15.0
  pin_code_fields: ^8.0.1
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.4.0
  share_plus: ^10.1.2
  shared_preferences: ^2.3.2
  sms_autofill: ^2.4.1
  url_launcher: ^6.3.1
dev_dependencies:
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  device_preview: ^1.2.0
  flutter_lints: ^3.0.0
  retrofit_generator: '>=8.0.0 <10.0.0'
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  package_rename: ^1.7.1
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
    - shorebird.yaml
flutter_intl:
  enabled: true
