name: aroodi_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.5+5000
environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  connectivity_plus: ^6.1.0
  country_flags: ^3.0.0
  cupertino_icons: ^1.0.6
  google_mobile_ads: ^5.2.0
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.2
  get_it: ^8.0.1
  json_annotation: ^4.9.0
  persistent_bottom_nav_bar: ^6.2.1
  photo_view: ^0.15.0
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.4.0
  shared_preferences: ^2.3.2
  firebase_core: ^3.6.0

  
dev_dependencies:
  build_runner: ^2.4.13
  retrofit_generator: '>=8.0.0 <10.0.0'
  json_serializable: ^6.8.0
  flutter_lints: ^3.0.0
  freezed: ^2.5.7
  flutter_test:
    sdk: flutter
  # dart run flutter_native_splash:create --path=flutter_native_splash.yaml
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/launcher_icon.jpg"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/launcher_icon.jpg"
    background_color: "#000000"
    theme_color: "#000000"
  windows:
    generate: true
    image_path: "assets/icons/launcher_icon.jpg"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icons/launcher_icon.jpg"
flutter_native_splash:
  color: "#FFFFFF"
  android_gravity: fill
  android_12:
    image: assets/icon/AppColors.white.png
  android: true
  ios: true
  web: true
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
