name: awfar_offer_app
description: "awfar_offer_app."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  connectivity_plus: ^6.1.0
  country_code_picker: ^3.1.0
  country_flags: ^3.0.0
  country_picker: ^2.0.27
  cupertino_icons: ^1.0.6
  device_info_plus: ^11.2.0
  dio: ^5.7.0
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_flavorizr: ^2.2.3
  flutter_launcher_icons: ^0.14.1
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.2
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.2
  font_awesome_flutter: ^10.8.0
  gap: ^3.0.1
  get_it: ^8.0.1
  google_mobile_ads: ^5.2.0
  googleapis_auth: ^1.6.0
  json_annotation: ^4.9.0
  motion_toast: ^2.11.0
  path_provider: ^2.1.5
  persistent_bottom_nav_bar: ^6.2.1
  photo_view: ^0.15.0
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.4.0
  share_plus: ^10.1.2
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.1
dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  package_rename: ^1.7.1
  retrofit_generator: '>=8.0.0 <10.0.0'
  device_preview: ^1.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - shorebird.yaml

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/launcher_icon.jpg"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/launcher_icon.jpg"
    background_color: "#000000"
    theme_color: "#000000"
  windows:
    generate: true
    image_path: "assets/icons/launcher_icon.jpg"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icons/launcher_icon.jpg"
flutter_native_splash:
  color: "#FFFFFF"
  android_gravity: fill
  android_12:
    image: assets/icon/AppColors.white.png
  android: true
  ios: true
  web: true

flutter_intl:
  enabled: true
