name: awfaroffers
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  connectivity_plus: ^6.1.0
  country_flags: ^3.0.0
  cupertino_icons: ^1.0.6
  dio: ^5.7.0
  firebase_core: ^3.6.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_launcher_icons: ^0.14.1
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.2
  get_it: ^8.0.1
  google_mobile_ads: ^5.2.0
  json_annotation: ^4.9.0
  persistent_bottom_nav_bar: ^6.2.1
  photo_view: ^0.15.0
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.4.0
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.1
  flutter_native_splash: ^2.4.2
dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^3.0.0
  package_rename: ^1.7.1
  freezed: ^2.5.7
  retrofit_generator: '>=8.0.0 <10.0.0'
  json_serializable: ^6.8.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/    
    - assets/icons/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
