// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2MqQrd_UO3uuYu2cnM7Ogulz0J8FNOCI',
    appId: '1:1067135384858:web:a478a25d518fec866e40a3',
    messagingSenderId: '1067135384858',
    projectId: 'com-awfaroffers-app-dev',
    authDomain: 'com-awfaroffers-app-dev.firebaseapp.com',
    storageBucket: 'com-awfaroffers-app-dev.firebasestorage.app',
    measurementId: 'G-WXLE6LDG5S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxn2y9018fOh8wVWJZc4zXEBEiFSWE_50',
    appId: '1:1067135384858:android:2a21e013fc06ec416e40a3',
    messagingSenderId: '1067135384858',
    projectId: 'com-awfaroffers-app-dev',
    storageBucket: 'com-awfaroffers-app-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdZGIfSxQvwfhpNOPFg2Hs2blWwXujIgg',
    appId: '1:1067135384858:ios:e09564a3b14234086e40a3',
    messagingSenderId: '1067135384858',
    projectId: 'com-awfaroffers-app-dev',
    storageBucket: 'com-awfaroffers-app-dev.firebasestorage.app',
    iosBundleId: 'com.awfaroffers.app.dev.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdZGIfSxQvwfhpNOPFg2Hs2blWwXujIgg',
    appId: '1:1067135384858:ios:83fde8b1c847e9ef6e40a3',
    messagingSenderId: '1067135384858',
    projectId: 'com-awfaroffers-app-dev',
    storageBucket: 'com-awfaroffers-app-dev.firebasestorage.app',
    iosBundleId: 'com.awfaroffers.app.dev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2MqQrd_UO3uuYu2cnM7Ogulz0J8FNOCI',
    appId: '1:1067135384858:web:e1e8e3ecf3a5d7996e40a3',
    messagingSenderId: '1067135384858',
    projectId: 'com-awfaroffers-app-dev',
    authDomain: 'com-awfaroffers-app-dev.firebaseapp.com',
    storageBucket: 'com-awfaroffers-app-dev.firebasestorage.app',
    measurementId: 'G-1F9SRSZT2M',
  );
}
