// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9JwYfw_cjdrZmFc1RlHgd0DITvHfYz0c',
    appId: '1:630596450299:web:d8bdc965ea323a833ffd5e',
    messagingSenderId: '630596450299',
    projectId: 'awfar-offers',
    authDomain: 'awfar-offers.firebaseapp.com',
    storageBucket: 'awfar-offers.firebasestorage.app',
    measurementId: 'G-0264FFCK73',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdz2VEKNdXNaxbWk5Fjfa4rjn-_S7gpe8',
    appId: '1:630596450299:android:1eab30b838ee19393ffd5e',
    messagingSenderId: '630596450299',
    projectId: 'awfar-offers',
    storageBucket: 'awfar-offers.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdRTOk5DrN2AsNiktHKY35s_V3lDp77RI',
    appId: '1:630596450299:ios:0ed0dc86304305aa3ffd5e',
    messagingSenderId: '630596450299',
    projectId: 'awfar-offers',
    storageBucket: 'awfar-offers.firebasestorage.app',
    iosBundleId: 'com.example.aroodiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdRTOk5DrN2AsNiktHKY35s_V3lDp77RI',
    appId: '1:630596450299:ios:0ed0dc86304305aa3ffd5e',
    messagingSenderId: '630596450299',
    projectId: 'awfar-offers',
    storageBucket: 'awfar-offers.firebasestorage.app',
    iosBundleId: 'com.example.aroodiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9JwYfw_cjdrZmFc1RlHgd0DITvHfYz0c',
    appId: '1:630596450299:web:9a9a48a9bfbab62e3ffd5e',
    messagingSenderId: '630596450299',
    projectId: 'awfar-offers',
    authDomain: 'awfar-offers.firebaseapp.com',
    storageBucket: 'awfar-offers.firebasestorage.app',
    measurementId: 'G-2PGC1QXBZD',
  );
}
