
name: Distribution

on: 
    repository_dispatch:
     types: [distribute]
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      #! توزيع نسخ التطبيق 
      - name: Upload Debug APK to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: app-debug
          file: build/app/outputs/flutter-apk/app-debug.apk
      - name: Upload Profile APK to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: app-profile
          file: build/app/outputs/flutter-apk/app-profile.apk
          debug: false
      - name: Upload Release APK to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: app-release
          file: build/app/outputs/flutter-apk/app-release.apk
          debug: false
      #! 9. Uploading architecture-specific APKs
      # - name: Upload app-x86_64 to Firebase App Distribution
      #   uses: wzieba/Firebase-Distribution-Github-Action@v1
      #   with:
      #     appId: ${{ secrets.FIREBASE_APP_ID }}
      #     serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
      #     groups: x86_64
      #     file: build/app/outputs/flutter-apk/app-x86_64-release.apk    
      - name: Upload app-arm64-v8a to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: arm64-v8a
          file: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk    
      
      - name: Upload app-armeabi-v7a to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: armeabi-v7a
          file: build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
