name: test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Cache Flutter SDK
        uses: actions/cache@v2
        with:
          path: ~/.flutter
          key: ${{ runner.os }}-flutter-${{ hashFiles('pubspec.yaml') }}

      - name: Install Flutter
        run: |
          if [ ! -d "$HOME/.flutter/bin" ]; then
            git clone https://github.com/flutter/flutter.git -b stable $HOME/.flutter
          fi
          echo "$HOME/.flutter/bin" >> $GITHUB_PATH
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with: 
          flutter-version: '3.24.4'
      
      - name: Increment versionCode and versionName
        id: version
        run: |
          # قراءة المعلومات من ملف version_info.txt أو تعيين القيم الافتراضية
          if [ -f version_info.txt ]; then
              read -r version_name version_code < version_info.txt
          else
              version_name="1.0.0"
              version_code="1"
          fi
          
          # زيادة versionCode
          new_version_code=$((version_code + 1))
          
          # زيادة versionName (patch)
          major_version=$(echo "$version_name" | cut -d. -f1)
          minor_version=$(echo "$version_name" | cut -d. -f2)
          patch_version=$(echo "$version_name" | cut -d. -f3)
          new_patch_version=$((patch_version + 1))
          new_version_name="${major_version}.${minor_version}.${new_patch_version}"
          
          # تحديث pubspec.yaml بإصدار جديد
          sed -i "s/^version: .*/version: ${new_version_name}+${new_version_code}/" pubspec.yaml
          
          # حفظ الأرقام الجديدة في ملف version_info.txt
          echo "$new_version_name $new_version_code" > version_info.txt
          
          # تعيين المتغيرات البيئية لتكون متاحة للمراحل الأخرى
          echo "versionName=$new_version_name" >> $GITHUB_ENV
          echo "versionCode=$new_version_code" >> $GITHUB_ENV    

      - name: Cache Pub Packages
        uses: actions/cache@v2
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('pubspec.yaml') }}    

      - name: Flutter pub get
        run: flutter pub get

      - name: Build APKs
        run: |
          flutter build apk --split-per-abi
      
      - name: Upload app-armeabi-v7a-release.apk to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: app-armeabi-v7a-release.apk                           
          file: build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
          releaseNotes: "app-armeabi-v7a-release.apk"
